title: Ministry of Law - Registry of Pawnbrokers
description: Description
url: https://rop.mlaw.gov.sg
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
favicon: /images/favicon-minlaw.ico
google-analytics: UA-10405444-16
permalink: none
baseurl: ""
defaults:
  - scope:
      path: ""
    values:
      layout: page
staging: https://staging.dbr7ka68peqcg.amplifyapp.com/
prod: https://master.dbr7ka68peqcg.amplifyapp.com/
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
colors:
  primary-color: "#a40935"
  secondary-color: "#a40935"
  media-colors:
    - title: media-color-one
      color: "#696969"
    - title: media-color-two
      color: "#800000"
    - title: media-color-three
      color: "#A0522D"
    - title: media-color-four
      color: "#866633"
    - title: media-color-five
      color: "#505050"
facebook-pixel: ""
shareicon: /images/isomer-logo.svg
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
