title: 'Ministry of Law - Registry of Pawnbrokers'
description: Description
url: 'https://rop.mlaw.gov.sg'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    information-for-pawnbrokers:
        output: true
    information-for-pawners:
        output: true
favicon: /images/favicon-minlaw.ico
google-analytics: UA-10405444-16
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
